# Generated by Django 5.2 on 2025-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('physician_name', models.CharField(max_length=200)),
                ('physician_email', models.EmailField(max_length=254)),
                ('physician_phone', models.CharField(max_length=20)),
                ('procedure_type', models.CharField(choices=[('xray', 'X-Ray'), ('ultrasound', 'Ultrasound')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('philhealth', 'PhilHealth'), ('hmo', 'HMO')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
