# Generated by Django 5.2.7 on 2025-10-08 06:24

import django.db.models.deletion
import xferDxApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=xferDxApp.models.dicom_upload_path)),
                ('study_id', models.CharField(default='', max_length=100, unique=True)),
                ('exam_priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=50)),
                ('clinical_history', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('metadata_extracted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_images', to='xferDxApp.patient')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
